language: node_js
dist: trusty
node_js:
  - "5"
cache:
  directories:
    - node_modules
install:
  - npm install
script: "npm run coverage"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"